# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
    
jobs:
  windows-build:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - PLATFORM: 'windows-64'
            PYTHON_ARCH: 'x64'
            VS_ARCH: 'amd64'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8.8"
    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt
        python -m pip install flake8
    - name: Init submodule
      run: |
        git submodule init
        git submodule update
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: build
      run: |
         python cmd_test.py --target_platform=windows64 --compiler=gcc -run_tests=true -download_godot=true


